= Test Case F08.UC15

|===
|Doc-ID: |TC-32-0815
|Datum: | 17.05.2025
|Test durchgeführt durch: | Nora Ramos
|===

== Beschreibung

Der Test soll sicherstellen, dass

**F08.UC15 – Ende des Spiels erkennen**

erfüllt werden kann.

== Annahmen und Voraussetzungen
- Das Spiel wurde korrekt gestartet und läuft fehlerfrei
- Ein vollständiges Kartenset ist vorhanden und alle Paare können korrekt erkannt werden
- Die Spielmechanik zählt korrekt mit, welche Kartenpaare bereits gefunden wurden
- Wenn alle Karten gefunden wurden, wir ein Screen angezeigt, wer wie viele Karten gefunden hat und wer der Gewinner ist.

== Testdaten
- 12 gültige Kartenpaare (24 Karten)
- Zwei Spieler
- Alle Kartenpaare wurden im Spielverlauf korrekt gefunden

== Auszuführende Schritte
. Spiel wird gestartet
. Spieler decken abwechselnd Karten auf und scannen diese bis alle Kartenpaare gefunden wurden.
. Das Spiel erkennt, dass keine Karten mehr übrig sind.
. Der Endbildschirm mit entsprechender Punktestand wird angezeigt.

== Erwartetes Ergebnis
- Sobald alle Kartenpaare korrekt gefunden wurden, erkennt das System das Spielende
- Der Bildschirm wechselt automatisch in einen Endzustand (mit Punktestand, Spiel beenden-Button, Restart-Option)
- Der Punktestand und Sieger werden angezeigt

== Erzieltes Ergebnis
Wenn alle Karten gefunden sind, wird der Sieger-Screen angezeigt. Punktestand ist korrekt berechnet.

== Bemerkungen
Test erfolgreich abgeschlossen. Keine funktionalen Abweichungen festgestellt.